#!/usr/bin/env python3
print("Patching library.cfg...")
import sys
user = sys.argv[1]
home = "/home/"+user
f = open(home+"/.thunder/library.cfg","a")
f.write("[16]\n")
f.write("NM = 0\n")
f.write("ID = 0\n")
f.write("CV = 0\n")
f.write("RN = 0\n")
f.write("[17]\n")
f.write("NM = 0\n")
f.write("ID = 0\n")
f.write("CV = 0\n")
f.write("RN = 0\n")
f.write("[18]\n")
f.write("NM = 0\n")
f.write("ID = 0\n")
f.write("CV = 0\n")
f.write("RN = 0\n")
f.write("[19]\n")
f.write("NM = 0\n")
f.write("ID = 0\n")
f.write("CV = 0\n")
f.write("RN = 0\n")
f.write("[20]\n")
f.write("NM = 0\n")
f.write("ID = 0\n")
f.write("CV = 0\n")
f.write("RN = 0\n")
