#!/bin/bash
echo "Thunder version:"
thunderversion=$(thunder-cli --version)
echo $thunderversion
# STABLE v1.0.0
if [[ $thunderversion == "Thunder is currently this version: STABLE Rev 1.0" ]]; then
echo "Updating thunder-cli..."
sudo cp thunder-cli /usr/local/bin/thunder-cli # To update Thunder version
fi
if [[ $thunderversion == "STABLE v1.0.1" ]]; then
echo "Adding config file..."
cp news.cfg ~/.thunder/news.cfg
echo "Updating thunder-cli..."
sudo cp thunder-cli /usr/local/bin/thunder-cli
fi
if [[ $thunderversion == "STABLE v1.0.2" ]]; then
echo "Updating thunder-cli..."
sudo cp thunder-cli /usr/local/bin/thunder-cli
fi
if [[ $thunderversion == "STABLE v1.0.3" ]]; then
echo "Updating thunder-cli..."
sudo cp thunder-cli /usr/local/bin/thunder-cli
fi
if [[ $thunderversion == "STABLE v1.0.4" ]]; then
echo "Updating thunder-cli..."
sudo cp thunder-cli /usr/local/bin/thunder-cli
python3 patches/update_v1.0.5.py $USER
fi
if [[ $thunderversion == "STABLE v1.0.5" ]]; then
echo "Updating thunder-cli..."
sudo cp thunder-cli /usr/local/bin/thunder-cli
cp mesa.cfg ~/.thunder/mesa.cfg
fi
if [[ $thunderversion == "STABLE v1.0.6" ]]; then
echo "Updating thunder-cli..."
sudo cp thunder-cli /usr/local/bin/thunder-cli
fi
if [[ $thunderversion == "STABLE v1.0.7" ]]; then
echo "Updating thunder-cli..."
sudo cp thunder-cli /usr/local/bin/thunder-cli
echo "New Version:"
thunder-cli --version
cp gallium.cfg ${HOME}/.thunder/gallium.cfg
python3 patches/update_v1.0.7.py $USER
fi
if [[ $thunderversion == "STABLE v1.0.8" ]]; then
echo "Updating thunder-cli..."
sudo cp thunder-cli /usr/local/bin/thunder-cli
fi
if [[ $thunderversion == "STABLE v1.0.9" ]]; then
echo "Updating thunder-cli..."
sudo cp thunder-cli /usr/local/bin/thunder-cli
fi
if [[ $thunderversion == "STABLE v1.1.0" ]]; then
echo "Updating thunder-cli..."
sudo cp thunder-cli /usr/local/bin/thunder-cli
fi
if [[ $thunderversion == "STABLE v1.1.1" ]]; then
echo "Updating thunder-cli..."
sudo cp thunder-cli /usr/local/bin/thunder-cli
fi
if [[ $thunderversion == "STABLE v1.1.2" ]]; then
echo "Updating thunder-cli..."
sudo cp thunder-cli /usr/local/bin/thunder-cli
fi
if [[ $thunderversion == "STABLE v1.1.3" ]]; then
echo "Updating thunder-cli..."
sudo cp thunder-cli /usr/local/bin/thunder-cli
fi
echo "Closing in 10 seconds. Please reopen Thunder for changes to take effect."
sleep 10s
